# docker build --rm --tag wip-repro-lexicon .

FROM jupyter/datascience-notebook

RUN conda install --yes 'nltk'
#RUN conda install --yes 'somecondapkg=x.y.z'
#RUN pip install 'somepippackage'
#RUN pip install 'somepippackage==a.b.c'
